# Generated by Django 5.2.18 on 2026-10-07 16:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True, verbose_name='Nama Kategori')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Produk')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Kode SKU')),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Harga (Rp)')),
                ('stok', models.PositiveIntegerField(default=0, verbose_name='Jumlah Stok')),
                ('aktif', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produk', to='core_app.kategori', verbose_name='Kategori Induk')),
            ],
            options={
                'ordering': ['-dibuat_pada'],
                'indexes': [models.Index(fields=['sku'], name='core_app_pr_sku_c9e559_idx'), models.Index(fields=['slug'], name='core_app_pr_slug_d67dfd_idx')],
            },
        ),
    ]
